version: '3.8'
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: caizmi
      POSTGRES_USER: caizmi
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
