ALTER TABLE venues
    ADD COLUMN IF NOT EXISTS country VARCHAR(100) NOT NULL DEFAULT 'Türkiye',
    ADD COLUMN IF NOT EXISTS working_hours JSONB,
    ADD COLUMN IF NOT EXISTS confirmation_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS is_double_verified BOOLEAN NOT NULL DEFAULT false;
